server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uo_taxes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

jwt:
  secretKey: QeThVmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E

user:
  defaultPassword: A1b2c3d4
  role: Student
